---
name: Publish Helm Charts

on:
  push:
    tags:
    - v0.*

jobs:
  release-helm-chart:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.VERSION }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.39.2
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configuring developer tools
      run: |
        task create-venv
        eval "$(task venv)"
        task install

    - name: Generate build tags
      id: get-version
      run: |
        eval "$(task venv)"
        source "scripts/functions.bash"

        scripts/detect-and-set-tag-version.bash
        echo "VERSION=$(cat ${{ github.workspace }}/VERSION)" >> "$GITHUB_ENV"
        echo "VERSION=$(cat ${{ github.workspace }}/VERSION)" >> "$GITHUB_OUTPUT"

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Set appVersion on chart.yaml
      run: |
        echo "Updating chart version to ${{ env.VERSION }}"
        sed -i.bak "s/version:.*$/version: ${{ env.VERSION }}/" charts/ecr-cleaner/Chart.yaml
        sed -i.bak "s/^appVersion:.*$/appVersion: ${{ env.VERSION }}/" charts/ecr-cleaner/Chart.yaml

    - name: Run helm-docs
      uses: losisin/helm-docs-github-action@v1
      with:
        chart-search-root: ./charts

    - name: Helm lint
      run: helm lint charts/ecr-cleaner

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        skip_existing: true

  update-chart-readme:
    runs-on: ubuntu-latest
    needs: release-helm-chart
    permissions:
      contents: write
    steps:
    - name: set version
      run: |
        echo "VERSION=${{ needs.release-helm-chart.outputs.version }}" >> "$GITHUB_ENV"

    - name: Wait for index build
      run: sleep 60

    - name: Checkout docs branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Download helm chart
      run: |
        helm repo add ecr-cleaner https://rahulinux.github.io/ecr-cleaner/
        helm pull ecr-cleaner/ecr-cleaner --version ${{ env.VERSION }}

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Update chart README
      run: |
        tar -zxvf ecr-cleaner-*.tgz  ecr-cleaner/README.md
        rm -rf ecr-cleaner-*.tgz
        mv -v ecr-cleaner/README.md README.md
        git add README.md
        git commit -m "[automated commit] Update chart README for release  ${{ env.VERSION }}"
        # display last commit
        git log -1 --stat -p
        git push origin gh-pages
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
