---
name: Publish Helm Charts

on:
  push:
    tags:
    - v0.*

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Set appVersion on chart.yaml
      run: |
        echo "Updating chart version to $GITHUB_REF_NAME"
        sed -i.bak "s/version:.*$/version: $GITHUB_REF_NAME/" charts/ecr-cleaner/Chart.yaml
        sed -i.bak "s/^appVersion:.*$/appVersion: $GITHUB_REF_NAME/" charts/ecr-cleaner/Chart.yaml

    - name: Run helm-docs
      uses: losisin/helm-docs-github-action@v1
      with:
        chart-search-root: ./charts

    - name: Helm lint
      run: helm lint charts/ecr-cleaner

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        skip_existing: true

  update-chart-readme:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Update chart README
      run: |
        git checkout gh-pages
        git checkout  $GITHUB_REF_NAME --  charts/ecr-cleaner/README.md
        mv -f charts/ecr-cleaner/README.md .
        rm -rf charts
        git add README.md
        git commit -m "[automated commit] Update chart README for release $GITHUB_REF_NAME"
        # display last commit
        git log -1 --stat -p
        git push gh-pages
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
