name: Build and Publish Docker Image

on:
  # Trigger only on v0.* tag pushes
  push:
    tags:
      - "v0.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configuring developer tools
        run: |
          task create-venv
          eval "$(task venv)"
          task setup

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building and pushing Docker images
        id: build
        run: |
          eval "$(task venv)"
          source "scripts/functions.bash"

          OWNER_REPO="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" # format: org/repo
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)

          TAG="$(get_tag_at_head)"
          if [ -z "$TAG" ]; then
            TAG="${{ github.sha }}"
          fi

          task docker-build -- \
            --platform linux/arm64,linux/x86_64 \
            --push \
            --tag "ghcr.io/$OWNER_REPO:${{ github.sha }}" \
            --tag "ghcr.io/$OWNER_REPO:$TAG" \
            --tag "ghcr.io/$OWNER_REPO:latest" \
            --tag "docker.io/${{ vars.DOCKERHUB_USERNAME }}/$REPO_NAME:${{ github.sha }}" \
            --tag "docker.io/${{ vars.DOCKERHUB_USERNAME }}/$REPO_NAME:$TAG" \
            --tag "docker.io/${{ vars.DOCKERHUB_USERNAME }}/$REPO_NAME:latest"

          # digest
          DOCKER_DIGEST="$(jq -r '.["containerimage.digest"]' build/build-metadata.json)"
          echo "digest=${DOCKER_DIGEST}" >&2
          echo "digest=${DOCKER_DIGEST}" >> "$GITHUB_OUTPUT"

      - name: Generate artifact attestation for GitHub Container Registry
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation for Docker Hub
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
